variables:
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_SECRET_ACCESS_KEY: "AKIAIFGV55AHYKXFKCFA"
  AWS_ACCESS_KEY_ID:   "9j6NhdHMMNczW03ZA/BkdWmiZjg66s7q9Hsqd/00"
  AWS_S3_LOCATION: "s3://s3-code-deploy-ec2/node-chat-app.zip"

image: ubuntu:latest

stages:
  - ver
  - deploy

job:
  stage: ver
  script:
    - ls

### DEPLOY ####################################################
job:
  stage: deploy
  # Script to run for deploying application to AWS
  script:
    - apt-get update
    - apt-get --quiet install --yes nodejs
    - apt-get  --quiet install --yes  npm
    - apt-get  --quiet install --yes  python-pip # AWS CLI requires python-pip, python is installed by default
    - pip install -U pip  # pip update 
    - pip install awscli  # AWS CLI installation
    - npm run build
    - ls
    #- $G distZip  # creates distribution zip for deployment
    # - aws s3 cp $BUNDLE_SRC $AWS_S3_LOCATION # Uploads the zipfile to S3 and expects the AWS Code Pipeline/Code Deploy to pick up
  # requires previous CI stages to succeed in order to execute






