image: ubuntu:latest

variables:
  #AWS_DEFAULT_REGION: us-east-1
  #AWS_SECRET_ACCESS_KEY: AKIAIFGV55AHYKXFKCFA
  #AWS_ACCESS_KEY_ID:   9j6NhdHMMNczW03ZA/BkdWmiZjg66s7q9Hsqd/00
  #AWS_S3_LOCATION: s3://s3-code-deploy-ec2/

stages:
  - ver
  - deploy

job:
  stage: ver
  script:
    - ls

### DEPLOY ####################################################
job:
  stage: deploy
  # Script to run for deploying application to AWS
  script:
    - apt-get update
    - apt-get --quiet install --yes nodejs
    - apt-get  --quiet install --yes  npm
    - apt-get  --quiet install --yes  python-pip # AWS CLI requires python-pip, python is installed by default
    - python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall  # pip update 
    - pip install awscli  # AWS CLI installation
    - npm install
    - npm run deploy
    - ls
    - echo $AWS_S3_LOCATION
    - aws s3 cp node-chat-app.zip s3://s3-code-deploy-ec2/node-chat-app.zip # Uploads the zipfile to S3 and expects the AWS Code Pipeline/Code Deploy to pick up
    
  # requires previous CI stages to succeed in order to execute






