variables:
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_SECRET_ACCESS_KEY: "AKIAIFGV55AHYKXFKCFA"
  AWS_ACCESS_KEY_ID:   "9j6NhdHMMNczW03ZA/BkdWmiZjg66s7q9Hsqd/00"
  AWS_S3_LOCATION: "s3://s3-code-deploy-ec2/node-chat-app.zip"