# Node docker image on which this would be run
image: node:8.9.0

#This command is run before actual stages start running
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install

stages:
  - test
  - deploy

# lint and test are two different jobs in the same stage.
# This allows us to run these two in parallel and making build faster

# Job 1:
#lint:
#  stage: test
#  script:
#    - npm run lint

# Job 2:
test:
  stage: test
  script:
    - npm run test
    # ToDo: Add coverage

deployToAWS:
  only:
    - develop
  stage: deploy
  script:
    #- bash deploy/aws-code-deploy/deploy.sh
    - apt-get update
    - apt-get --quiet install --yes nodejs
    - apt-get  --quiet install --yes  npm
    - apt-get  --quiet install --yes  python-pip # AWS CLI requires python-pip, python is installed by default
    - python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall  # pip update 
    - pip install awscli  # AWS CLI installation
    - npm install
    - npm run deploy
    - ls
    - echo $AWS_SECRET_ACCESS_KEY
    - aws s3 cp node-chat-app.zip $AWS_S3_LOCATION 
