image: ubuntu:latest

variables:

stages:
  - ver
  - deploy

job:
  stage: ver
  script:
    - ls

### DEPLOY ####################################################
job:
  stage: deploy
  # Script to run for deploying application to AWS
  variables:
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_S3_LOCATION: s3://s3-code-deploy-ec2
  script:
    - apt-get update
    - apt-get --quiet install --yes nodejs
    - apt-get  --quiet install --yes  npm
    - apt-get  --quiet install --yes  python-pip # AWS CLI requires python-pip, python is installed by default
    - python3 -m pip uninstall pip && sudo apt install python3-pip --reinstall  # pip update 
    - pip install awscli  # AWS CLI installation
    - npm install
    - npm run deploy
    - ls
    - echo $AWS_SECRET_ACCESS_KEY
    - aws s3 cp node-chat-app.zip $AWS_S3_LOCATION # Uploads the zipfile to S3 and expects the AWS Code Pipeline/Code Deploy to pick up
    
  # requires previous CI stages to succeed in order to execute






