version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-node-chat-app
hooks:
  AfterInstall:
    - location: deploy/scripts/app-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: deploy/scripts/app-start.sh
      runas: root
      timeout: 60
